import { Module } from '@/core/types';

const LESSON_CONTENT = `
# 1. Lesson Title
**Topic:** Parametric Equations
**Unit:** A2 1 Pure Mathematics (A21)

## 2. Specification Alignment

| LO ID | CCEA Specification Point |
|---|---|
| A21-CG-LO001 | Parametric equations of curves and conversion between Cartesian and parametric forms |
| A21-CG-LO002 | Use parametric equations in modelling in a variety of contexts |

## 3. Learning Objectives
By the end of this lesson, you should be able to:
* Understand the difference between Cartesian and parametric equations.
* Convert parametric equations into a single Cartesian equation using algebraic substitution, logarithms, or trigonometric identities.
* Determine the domain and range of a Cartesian function based on the restrictions placed on the parameter.
* Find the coordinates of points where a parametric curve intersects the coordinate axes or a given straight line.
* Use parametric equations to model real-world scenarios, such as 2D motion over time, and critique the limitations of these models.

## 4. Big Picture Explanation
Typically, we describe a curve using a **Cartesian equation** connecting $x$ directly to $y$. 
However, in many real-world situations, it is much more useful to describe the $x$ and $y$ coordinates separately as they change over time. By defining $x$ and $y$ separately in terms of a third variable (the **parameter**), we create **parametric equations**. This allows us to easily model complex paths which would be difficult or impossible to write as a single $y = f(x)$ Cartesian equation. 

## 5. Key Definitions and Notation
* **Parameter:** A third variable (usually $t$ for time, or $\\theta$ for an angle) used to define $x$ and $y$.
* **Parametric Equations:** A pair of equations that express the coordinates as functions of a parameter (e.g., $x = 2t$, $y = t^2$).
* **Domain of a Parametric Curve:** The possible $x$-values generated by the parameter.
* **Range of a Parametric Curve:** The possible $y$-values generated by the parameter.

## 6. Core Theory

### 6.1 Converting Parametric to Cartesian
Your goal is to **eliminate the parameter**. 
Make the parameter the subject of one equation, and substitute it into the other.

[VISUAL PLACEHOLDER: A21ParametricEquationsSVG001 | Parametric Parabola with Time Stamps]

### 6.2 Converting with Trigonometric Identities
Use trigonometric identities to link the $x$ and $y$ equations together.
* **$\\sin t$ and $\\cos t$:** Use $\\sin^2 t + \\cos^2 t \\equiv 1$.
* **$\\sec t$ and $\\tan t$:** Use $1 + \\tan^2 t \\equiv \\sec^2 t$.
* **Double angles:** Use double angle formulae like $\\cos 2t \\equiv 1 - 2\\sin^2 t$.

### 6.3 Intersections with Axes and Lines
To find where a parametric curve crosses an axis or a line, **stay in the parametric world**.
* **Crossing the $x$-axis:** Set $y = 0$, solve for $t$, substitute $t$ into $x$.
* **Intersecting a line:** Substitute the parametric expressions directly into the line's equation.

[VISUAL PLACEHOLDER: A21ParametricEquationsMMD001 | Intersection Strategy Flowchart]

### 6.4 Modelling with Parametric Equations
Parametric equations are perfect for modelling 2D motion where $t$ represents time. Always check the domain of $t$ to ensure the model is physically realistic.

[VISUAL PLACEHOLDER: A21ParametricEquationsTikZ001 | Figure Skater Curve]

## 7. Interactive Learning Widgets

[INTERACTIVE PLACEHOLDER: A21ParametricEquationsWidget001 | Parametric Curve Plotter]

## 8. Common Mistakes and Exam Traps
* **Converting to Cartesian unnecessarily:** If finding points of intersection, substituting $x(t)$ and $y(t)$ into a line equation is much less prone to error than finding $y = f(x)$.
* **Ignoring domain restrictions:** A full parabola equation might only represent a small arc if $t$ is restricted.
* **Forgetting that trigonometric functions repeat:** When solving $y = 0$ for $y = \\sin(10t)$, there are multiple solutions.

## 9. Practice Questions
1. A curve has parametric equations $x = 3t - 1$ and $y = t^2 + 2$. Find the Cartesian equation.
2. A curve has parametric equations $x = 3\\cos \\theta$ and $y = 3\\sin \\theta$. Find the Cartesian equation.
3. A curve is defined by $x = t - 2$ and $y = t^2 - 4t$. Find where the curve intersects the $x$-axis.
`;

export const A21_08_MODULE: Module = {
  id: "A21-08",
  title: "Parametric Equations",
  type: "Pure Mathematics",
  overview: "Master parametric equations to model complex 2D curves and motion over time.",
  learningOutcomes: [
    { id: "A21-CG-LO001", text: "Parametric to Cartesian conversions" },
    { id: "A21-CG-LO002", text: "Parametric modelling" }
  ],
  lessons: [
    {
      id: "A21-08-Lesson",
      title: "Parametric Equations",
      visualId: "A21-Parametric-Equations",
      type: "Pure Mathematics",
      content: LESSON_CONTENT,
      loIds: ["A21-CG-LO001", "A21-CG-LO002"]
    }
  ]
};
