import React from 'react';
import { DiagramPanel } from '@/core/diagram-engine/DiagramPanel';

const htmlSource = "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>Definite Integral Calculator</title>\n  <style>\n    body { font-family: sans-serif; line-height: 1.4; margin: 20px; max-width: 700px; }\n    label { display: block; margin-top: 10px; }\n    input { width: 80px; }\n    .result { margin-top: 15px; padding: 10px; background: #f9f9f9; border: 1px solid #ccc; }\n    .warning { color: #a00; }\n  </style>\n</head>\n<body>\n  <h2>Definite Integral Calculator</h2>\n  <p>Compute <em>∫<sub>a</sub><sup>b</sup> a·x<sup>n</sup> dx</em>.  The antiderivative and the evaluated result are shown below.</p>\n  <label>Exponent n: <input type=\"number\" id=\"n2\" step=\"0.5\" value=\"2\"></label>\n  <label>Coefficient a: <input type=\"number\" id=\"a2\" step=\"0.5\" value=\"1\"></label>\n  <label>Lower limit a: <input type=\"number\" id=\"lower\" step=\"0.5\" value=\"0\"></label>\n  <label>Upper limit b: <input type=\"number\" id=\"upper\" step=\"0.5\" value=\"2\"></label>\n  <div id=\"out2\" class=\"result\"></div>\n  <script>\n    function update2() {\n      var n = parseFloat(document.getElementById('n2').value);\n      var a = parseFloat(document.getElementById('a2').value);\n      var lower = parseFloat(document.getElementById('lower').value);\n      var upper = parseFloat(document.getElementById('upper').value);\n      var out = document.getElementById('out2');\n      if ([n,a,lower,upper].some(function(v){ return isNaN(v); })) {\n        out.innerHTML = '<span class=\"warning\">Enter numeric values.</span>';\n        return;\n      }\n      var antiderivative;\n      var result;\n      if (Math.abs(n + 1) < 1e-8) {\n        antiderivative = a.toFixed(3) + '·ln|x| + C';\n        if (lower <= 0 || upper <= 0) {\n          result = 'Error: limits must be positive for ln|x|.';\n        } else {\n          result = a * Math.log(Math.abs(upper / lower));\n          result = 'Result: ' + result.toFixed(6);\n        }\n      } else {\n        var newPow = n + 1;\n        var coeff = a / newPow;\n        var coeffStr = Math.abs(coeff - Math.round(coeff)) < 1e-6 ? Math.round(coeff).toString() : coeff.toFixed(6);\n        antiderivative = coeffStr + '·x^' + newPow + ' + C';\n        var F = function(x) { return coeff * Math.pow(x, newPow); };\n        var val = F(upper) - F(lower);\n        result = 'Result: ' + val.toFixed(6);\n      }\n      out.innerHTML = '<strong>Antiderivative:</strong> ' + antiderivative + '<br><strong>' + result + '</strong>';\n    }\n    document.getElementById('n2').addEventListener('input', update2);\n    document.getElementById('a2').addEventListener('input', update2);\n    document.getElementById('lower').addEventListener('input', update2);\n    document.getElementById('upper').addEventListener('input', update2);\n    update2();\n  </script>\n</body>\n</html>";

export const AS1IntegrationLessonWIDGET002: React.FC = () => (
  <DiagramPanel title={"Definite Integral Calculator"} analysis={null} wide>
    <iframe
      title={"AS1-Integration-Lesson-WIDGET-002"}
      srcDoc={htmlSource}
      sandbox="allow-scripts"
      className="min-h-[540px] w-full rounded-xl border border-zinc-800 bg-white"
    />
  </DiagramPanel>
);
