import React from 'react';
import { DiagramPanel } from '@/core/diagram-engine/DiagramPanel';
import { LuxurySVGWrapper } from '@/core/diagram-engine/LuxurySVGWrapper';

const svgSource = "<svg width=\"550\" height=\"185\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Power rule table\">\n  <rect x=\"0\" y=\"0\" width=\"550\" height=\"185\" fill=\"white\" stroke=\"black\" />\n  <!-- Header row -->\n  <rect x=\"0\" y=\"0\" width=\"550\" height=\"35\" fill=\"#e6f2ff\" stroke=\"black\" />\n  <text x=\"60\" y=\"22\" font-family=\"Arial\" font-size=\"14\" font-weight=\"bold\">Function \\(y\\)</text>\n  <text x=\"240\" y=\"22\" font-family=\"Arial\" font-size=\"14\" font-weight=\"bold\">Derivative \\(dy/dx\\)</text>\n  <text x=\"420\" y=\"22\" font-family=\"Arial\" font-size=\"14\" font-weight=\"bold\">Notes</text>\n  <!-- Row: general power -->\n  <rect x=\"0\" y=\"35\" width=\"550\" height=\"30\" fill=\"#f9f9f9\" stroke=\"black\" />\n  <text x=\"35\" y=\"55\" font-family=\"Arial\" font-size=\"13\">\\(x^n\\)</text>\n  <text x=\"240\" y=\"55\" font-family=\"Arial\" font-size=\"13\">\\(n\\,x^{n-1}\\)</text>\n  <text x=\"420\" y=\"55\" font-family=\"Arial\" font-size=\"13\">General power rule</text>\n  <!-- Row: constant -->\n  <rect x=\"0\" y=\"65\" width=\"550\" height=\"30\" fill=\"white\" stroke=\"black\" />\n  <text x=\"35\" y=\"85\" font-family=\"Arial\" font-size=\"13\">\\(c\\) (constant)</text>\n  <text x=\"240\" y=\"85\" font-family=\"Arial\" font-size=\"13\">0</text>\n  <text x=\"420\" y=\"85\" font-family=\"Arial\" font-size=\"13\">Constants vanish</text>\n  <!-- Row: negative exponent -->\n  <rect x=\"0\" y=\"95\" width=\"550\" height=\"30\" fill=\"#f9f9f9\" stroke=\"black\" />\n  <text x=\"35\" y=\"115\" font-family=\"Arial\" font-size=\"13\">\\(x^{-n}\\)</text>\n  <text x=\"240\" y=\"115\" font-family=\"Arial\" font-size=\"13\">\\(-n\\,x^{-n-1}\\)</text>\n  <text x=\"420\" y=\"115\" font-family=\"Arial\" font-size=\"13\">Negative powers allowed</text>\n  <!-- Row: reciprocal -->\n  <rect x=\"0\" y=\"125\" width=\"550\" height=\"30\" fill=\"white\" stroke=\"black\" />\n  <text x=\"35\" y=\"145\" font-family=\"Arial\" font-size=\"13\">\\(\\dfrac{1}{x}\\)</text>\n  <text x=\"240\" y=\"145\" font-family=\"Arial\" font-size=\"13\">\\(-\\dfrac{1}{x^2}\\)</text>\n  <text x=\"420\" y=\"145\" font-family=\"Arial\" font-size=\"13\">Special case of \\(x^{-1}\\)</text>\n  <!-- Row: square root -->\n  <rect x=\"0\" y=\"155\" width=\"550\" height=\"30\" fill=\"#f9f9f9\" stroke=\"black\" />\n  <text x=\"35\" y=\"175\" font-family=\"Arial\" font-size=\"13\">\\(\\sqrt{x}=x^{1/2}\\)</text>\n  <text x=\"240\" y=\"175\" font-family=\"Arial\" font-size=\"13\">\\(\\tfrac{1}{2} x^{-1/2}\\)</text>\n  <text x=\"420\" y=\"175\" font-family=\"Arial\" font-size=\"13\">Fractional exponent case</text>\n</svg>";

export const AS1DifferentiationLessonSVG002: React.FC = () => (
  <DiagramPanel title={"Power Rule and Special Cases"} analysis={null}>
    <LuxurySVGWrapper svgSource={svgSource} className="w-full max-h-[560px] overflow-auto text-foreground [&_svg]:max-w-full [&_svg]:h-auto" />
  </DiagramPanel>
);
