import React from 'react';
import { DiagramPanel } from '@/core/diagram-engine/DiagramPanel';
import { LuxurySVGWrapper } from '@/core/diagram-engine/LuxurySVGWrapper';

const svgSource = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"920\" height=\"520\" viewBox=\"0 0 920 520\" role=\"img\" aria-label=\"Straightening curves with logarithms summary\">\n  <rect width=\"920\" height=\"520\" fill=\"#ffffff\"/>\n  <text x=\"460\" y=\"44\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"27\" font-weight=\"700\">Optional Extension: Straightening Curves with Logs</text>\n  <text x=\"460\" y=\"73\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"14\">Useful for enrichment; not treated as core CCEA AS1 content here.</text>\n\n  <rect x=\"55\" y=\"115\" width=\"390\" height=\"285\" rx=\"16\" fill=\"#f4f8ff\" stroke=\"#2f5da8\" stroke-width=\"2\"/>\n  <text x=\"250\" y=\"150\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"21\" font-weight=\"700\">Exponential model</text>\n  <text x=\"250\" y=\"190\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"21\">y = A e^(kx)</text>\n  <text x=\"95\" y=\"238\" font-family=\"Arial, sans-serif\" font-size=\"17\">Take natural logs:</text>\n  <text x=\"95\" y=\"275\" font-family=\"Arial, sans-serif\" font-size=\"18\">ln y = kx + ln A</text>\n  <text x=\"95\" y=\"322\" font-family=\"Arial, sans-serif\" font-size=\"16\">Plot ln y against x.</text>\n  <text x=\"95\" y=\"356\" font-family=\"Arial, sans-serif\" font-size=\"16\">Gradient = k; intercept = ln A.</text>\n\n  <rect x=\"475\" y=\"115\" width=\"390\" height=\"285\" rx=\"16\" fill=\"#fff8ed\" stroke=\"#c47b00\" stroke-width=\"2\"/>\n  <text x=\"670\" y=\"150\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"21\" font-weight=\"700\">Power-law model</text>\n  <text x=\"670\" y=\"190\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"21\">y = a x^n</text>\n  <text x=\"515\" y=\"238\" font-family=\"Arial, sans-serif\" font-size=\"17\">Take logs:</text>\n  <text x=\"515\" y=\"275\" font-family=\"Arial, sans-serif\" font-size=\"18\">log y = n log x + log a</text>\n  <text x=\"515\" y=\"322\" font-family=\"Arial, sans-serif\" font-size=\"16\">Plot log y against log x.</text>\n  <text x=\"515\" y=\"356\" font-family=\"Arial, sans-serif\" font-size=\"16\">Gradient = n; intercept = log a.</text>\n\n  <rect x=\"150\" y=\"435\" width=\"620\" height=\"42\" rx=\"12\" fill=\"#fff3f3\" stroke=\"#b54848\" stroke-width=\"2\"/>\n  <text x=\"460\" y=\"462\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"15\" font-weight=\"700\">Always state which log base is being used and keep units/context in the final model.</text>\n</svg>";

export const AS1ExponentialsLogarithmsLessonSVG004: React.FC = () => (
  <DiagramPanel title={"Straightening curves with logarithms summary"} analysis={null}>
    <LuxurySVGWrapper svgSource={svgSource} className="w-full max-h-[560px] overflow-auto text-foreground [&_svg]:max-w-full [&_svg]:h-auto" />
  </DiagramPanel>
);
