import React from 'react';
import { DiagramPanel } from '@/core/diagram-engine/DiagramPanel';

const svgSource = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"880\" height=\"500\" viewBox=\"0 0 880 500\" role=\"img\" aria-label=\"Domain and method warning card\">\n  <rect width=\"880\" height=\"500\" fill=\"#ffffff\"/>\n  <text x=\"440\" y=\"42\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"28\" font-weight=\"700\">Before You Solve: Check These</text>\n\n  <rect x=\"45\" y=\"80\" width=\"390\" height=\"330\" rx=\"16\" fill=\"#fff3f3\" stroke=\"#b54848\" stroke-width=\"2\"/>\n  <text x=\"240\" y=\"120\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"21\" font-weight=\"700\">Logarithm Restrictions</text>\n  <text x=\"80\" y=\"165\" font-family=\"Arial, sans-serif\" font-size=\"18\">1. Base a must satisfy a &gt; 0.</text>\n  <text x=\"80\" y=\"205\" font-family=\"Arial, sans-serif\" font-size=\"18\">2. Base a must not equal 1.</text>\n  <text x=\"80\" y=\"245\" font-family=\"Arial, sans-serif\" font-size=\"18\">3. Every log input must be positive.</text>\n  <text x=\"80\" y=\"285\" font-family=\"Arial, sans-serif\" font-size=\"18\">4. Candidate answers can be rejected.</text>\n  <text x=\"80\" y=\"335\" font-family=\"Arial, sans-serif\" font-size=\"15\">Example: log(x - 2) needs x - 2 &gt; 0, so x &gt; 2.</text>\n\n  <rect x=\"475\" y=\"80\" width=\"390\" height=\"330\" rx=\"16\" fill=\"#f4f8ff\" stroke=\"#2f5da8\" stroke-width=\"2\"/>\n  <text x=\"670\" y=\"120\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"21\" font-weight=\"700\">Method Choices</text>\n  <text x=\"510\" y=\"165\" font-family=\"Arial, sans-serif\" font-size=\"18\">• Same base possible?</text>\n  <text x=\"535\" y=\"195\" font-family=\"Arial, sans-serif\" font-size=\"15\">Rewrite and equate exponents.</text>\n  <text x=\"510\" y=\"240\" font-family=\"Arial, sans-serif\" font-size=\"18\">• Unknown in exponent?</text>\n  <text x=\"535\" y=\"270\" font-family=\"Arial, sans-serif\" font-size=\"15\">Take logs or natural logs.</text>\n  <text x=\"510\" y=\"315\" font-family=\"Arial, sans-serif\" font-size=\"18\">• Logs in equation?</text>\n  <text x=\"535\" y=\"345\" font-family=\"Arial, sans-serif\" font-size=\"15\">Write restrictions before solving.</text>\n\n  <rect x=\"120\" y=\"435\" width=\"640\" height=\"42\" rx=\"12\" fill=\"#ecf7ec\" stroke=\"#4f9151\" stroke-width=\"2\"/>\n  <text x=\"440\" y=\"462\" text-anchor=\"middle\" font-family=\"Arial, sans-serif\" font-size=\"16\" font-weight=\"700\">A correct-looking algebraic solution is not final until the original equation has been checked.</text>\n</svg>";

export const AS1ExponentialsLogarithmsLessonSVG003: React.FC = () => (
  <DiagramPanel title={"Domain and method warning card"} analysis={null}>
    <div
      className="w-full max-h-[560px] overflow-auto text-zinc-100 [&_svg]:max-w-full [&_svg]:h-auto"
      dangerouslySetInnerHTML={{ __html: svgSource }}
    />
  </DiagramPanel>
);
