import React from 'react';
import { DiagramPanel } from '@/core/diagram-engine/DiagramPanel';

const svgSource = "<svg width=\"600\" height=\"360\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"Arial, sans-serif\">\n  <!-- Background -->\n  <rect x=\"0\" y=\"0\" width=\"600\" height=\"360\" fill=\"#fcfcfc\" stroke=\"#bbbbbb\"/>\n  <!-- Title -->\n  <text x=\"300\" y=\"30\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\">Key Vector Formulas</text>\n  <!-- Box 1: Addition -->\n  <rect x=\"20\" y=\"60\" width=\"260\" height=\"90\" rx=\"8\" ry=\"8\" fill=\"#e8f5e9\" stroke=\"#66bb6a\"/>\n  <text x=\"150\" y=\"80\" font-size=\"14\" font-weight=\"bold\" text-anchor=\"middle\">Vector Addition</text>\n  <text x=\"30\" y=\"105\" font-size=\"12\">If \\(\\mathbf{a}=(x_1,y_1)\\) and \\(\\mathbf{b}=(x_2,y_2)\\),</text>\n  <text x=\"30\" y=\"123\" font-size=\"12\">then \\(\\mathbf{a}+\\mathbf{b}=(x_1+x_2,\\,y_1+y_2)\\).</text>\n  <!-- Box 2: Scalar multiple -->\n  <rect x=\"320\" y=\"60\" width=\"260\" height=\"90\" rx=\"8\" ry=\"8\" fill=\"#e3f2fd\" stroke=\"#42a5f5\"/>\n  <text x=\"450\" y=\"80\" font-size=\"14\" font-weight=\"bold\" text-anchor=\"middle\">Scalar Multiple</text>\n  <text x=\"330\" y=\"105\" font-size=\"12\">For scalar \\(k\\) and vector \\(\\mathbf{a}=(x,y)\\),</text>\n  <text x=\"330\" y=\"123\" font-size=\"12\">\\(k\\mathbf{a}=(kx,\\,ky)\\).</text>\n  <!-- Box 3: Magnitude & Direction -->\n  <rect x=\"20\" y=\"170\" width=\"260\" height=\"130\" rx=\"8\" ry=\"8\" fill=\"#fff3e0\" stroke=\"#ffa726\"/>\n  <text x=\"150\" y=\"190\" font-size=\"14\" font-weight=\"bold\" text-anchor=\"middle\">Magnitude &amp; Direction</text>\n  <text x=\"30\" y=\"215\" font-size=\"12\">\\(|\\mathbf{a}|=\\sqrt{x^2+y^2}\\)</text>\n  <text x=\"30\" y=\"233\" font-size=\"12\">\\(\\theta=\\tan^{-1}(y/x)\\;\\) (quadrant check)</text>\n  <text x=\"30\" y=\"251\" font-size=\"12\">\\(x=|\\mathbf{a}|\\cos\\theta,\\;y=|\\mathbf{a}|\\sin\\theta\\)</text>\n  <!-- Box 4: Position & Distance -->\n  <rect x=\"320\" y=\"170\" width=\"260\" height=\"130\" rx=\"8\" ry=\"8\" fill=\"#f3e5f5\" stroke=\"#ab47bc\"/>\n  <text x=\"450\" y=\"190\" font-size=\"14\" font-weight=\"bold\" text-anchor=\"middle\">Position &amp; Distance</text>\n  <text x=\"330\" y=\"215\" font-size=\"12\">Position vector of \\(P\\): \\(\\overrightarrow{OP}=(x,y)\\)</text>\n  <text x=\"330\" y=\"233\" font-size=\"12\">Distance between \\(P\\) and \\(Q\\): \\(|\\mathbf{q}-\\mathbf{p}|\\)</text>\n  <text x=\"330\" y=\"251\" font-size=\"12\">Distance travelled = speed × time</text>\n</svg>";

export const AS1VectorsLessonSVG001: React.FC = () => (
  <DiagramPanel title={"Summary of Key Vector Formulas"} analysis={null}>
    <div
      className="w-full max-h-[560px] overflow-auto text-zinc-100 [&_svg]:max-w-full [&_svg]:h-auto"
      dangerouslySetInnerHTML={{ __html: svgSource }}
    />
  </DiagramPanel>
);
