import * as P1 from './P1-Algebra & Functions';
import * as P2 from './P2-Co-ordinate geometry in the 𝒙, 𝒚 plane';
import * as P3 from './P3-Sequences and series';
import * as P4 from './P4-Trigonometry';
import * as P5 from './P5-Exponentials and logarithms';
import * as P6 from './P6-Differentiation';
import * as P7 from './P7-Integration';
import * as P8 from './P8-Vectors';

export const VisualRegistry = {
  P1,
  P2,
  P3,
  P4,
  P5,
  P6,
  P7,
  P8,
} as const;
export type ModuleKey = keyof typeof VisualRegistry;

export const AS1_SHORT_ID_MAPPING: Record<string, { module: ModuleKey; component: string }> = {
  "AS1-Binomial-Expansion-Lesson-MMD-001": { module: "P3" as ModuleKey, component: "AS1BinomialExpansionLessonMMD001" },
  "AS1-Binomial-Expansion-Lesson-SVG-001": { module: "P3" as ModuleKey, component: "AS1BinomialExpansionLessonSVG001" },
  "AS1-Binomial-Expansion-Lesson-TIKZ-001": { module: "P3" as ModuleKey, component: "AS1BinomialExpansionLessonTIKZ001" },
  "AS1-Binomial-Expansion-Lesson-WIDGET-001": { module: "P3" as ModuleKey, component: "AS1BinomialExpansionLessonWIDGET001" },
  "AS1-Binomial-Expansion-Lesson-WIDGET-002": { module: "P3" as ModuleKey, component: "AS1BinomialExpansionLessonWIDGET002" },
  "AS1-Binomial-Expansion-Lesson-WIDGET-003": { module: "P3" as ModuleKey, component: "AS1BinomialExpansionLessonWIDGET003" },
  "AS1-Differentiation-Lesson-MMD-001": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonMMD001" },
  "AS1-Differentiation-Lesson-MMD-002": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonMMD002" },
  "AS1-Differentiation-Lesson-SVG-001": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonSVG001" },
  "AS1-Differentiation-Lesson-SVG-002": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonSVG002" },
  "AS1-Differentiation-Lesson-SVG-003": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonSVG003" },
  "AS1-Differentiation-Lesson-TIKZ-001": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonTIKZ001" },
  "AS1-Differentiation-Lesson-TIKZ-002": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonTIKZ002" },
  "AS1-Differentiation-Lesson-TIKZ-003": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonTIKZ003" },
  "AS1-Differentiation-Lesson-WIDGET-001": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonWIDGET001" },
  "AS1-Differentiation-Lesson-WIDGET-002": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonWIDGET002" },
  "AS1-Differentiation-Lesson-WIDGET-003": { module: "P6" as ModuleKey, component: "AS1DifferentiationLessonWIDGET003" },
  "AS1-Exponentials-Logarithms-Lesson-MMD-001": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonMMD001" },
  "AS1-Exponentials-Logarithms-Lesson-MMD-002": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonMMD002" },
  "AS1-Exponentials-Logarithms-Lesson-MMD-003": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonMMD003" },
  "AS1-Exponentials-Logarithms-Lesson-MMD-004": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonMMD004" },
  "AS1-Exponentials-Logarithms-Lesson-MMD-005": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonMMD005" },
  "AS1-Exponentials-Logarithms-Lesson-SVG-001": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonSVG001" },
  "AS1-Exponentials-Logarithms-Lesson-SVG-002": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonSVG002" },
  "AS1-Exponentials-Logarithms-Lesson-SVG-003": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonSVG003" },
  "AS1-Exponentials-Logarithms-Lesson-SVG-004": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonSVG004" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-001": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ001" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-002": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ002" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-003": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ003" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-004": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ004" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-005": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ005" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-006": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ006" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-007": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ007" },
  "AS1-Exponentials-Logarithms-Lesson-TIKZ-008": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonTIKZ008" },
  "AS1-Exponentials-Logarithms-Lesson-WIDGET-001": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonWIDGET001" },
  "AS1-Exponentials-Logarithms-Lesson-WIDGET-002": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonWIDGET002" },
  "AS1-Exponentials-Logarithms-Lesson-WIDGET-003": { module: "P5" as ModuleKey, component: "AS1ExponentialsLogarithmsLessonWIDGET003" },
  "AS1-Indices-Surds-Lesson-MMD-001": { module: "P1" as ModuleKey, component: "AS1IndicesSurdsLessonMMD001" },
  "AS1-Indices-Surds-Lesson-MMD-002": { module: "P1" as ModuleKey, component: "AS1IndicesSurdsLessonMMD002" },
  "AS1-Indices-Surds-Lesson-SVG-001": { module: "P1" as ModuleKey, component: "AS1IndicesSurdsLessonSVG001" },
  "AS1-Indices-Surds-Lesson-TIKZ-001": { module: "P1" as ModuleKey, component: "AS1IndicesSurdsLessonTIKZ001" },
  "AS1-Indices-Surds-Lesson-WIDGET-001": { module: "P1" as ModuleKey, component: "AS1IndicesSurdsLessonWIDGET001" },
  "AS1-Indices-Surds-Lesson-WIDGET-002": { module: "P1" as ModuleKey, component: "AS1IndicesSurdsLessonWIDGET002" },
  "AS1-Indices-Surds-Lesson-WIDGET-003": { module: "P1" as ModuleKey, component: "AS1IndicesSurdsLessonWIDGET003" },
  "AS1-Integration-Lesson-MMD-001": { module: "P7" as ModuleKey, component: "AS1IntegrationLessonMMD001" },
  "AS1-Integration-Lesson-SVG-001": { module: "P7" as ModuleKey, component: "AS1IntegrationLessonSVG001" },
  "AS1-Integration-Lesson-TIKZ-001": { module: "P7" as ModuleKey, component: "AS1IntegrationLessonTIKZ001" },
  "AS1-Integration-Lesson-TIKZ-002": { module: "P7" as ModuleKey, component: "AS1IntegrationLessonTIKZ002" },
  "AS1-Integration-Lesson-WIDGET-001": { module: "P7" as ModuleKey, component: "AS1IntegrationLessonWIDGET001" },
  "AS1-Integration-Lesson-WIDGET-002": { module: "P7" as ModuleKey, component: "AS1IntegrationLessonWIDGET002" },
  "AS1-Integration-Lesson-WIDGET-003": { module: "P7" as ModuleKey, component: "AS1IntegrationLessonWIDGET003" },
  "AS1-P1-Transformations-Lesson-MMD-001": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonMMD001" },
  "AS1-P1-Transformations-Lesson-MMD-002": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonMMD002" },
  "AS1-P1-Transformations-Lesson-SVG-001": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonSVG001" },
  "AS1-P1-Transformations-Lesson-TIKZ-001": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonTIKZ001" },
  "AS1-P1-Transformations-Lesson-TIKZ-002": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonTIKZ002" },
  "AS1-P1-Transformations-Lesson-TIKZ-003": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonTIKZ003" },
  "AS1-P1-Transformations-Lesson-TIKZ-004": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonTIKZ004" },
  "AS1-P1-Transformations-Lesson-TIKZ-005": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonTIKZ005" },
  "AS1-P1-Transformations-Lesson-WIDGET-001": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonWIDGET001" },
  "AS1-P1-Transformations-Lesson-WIDGET-002": { module: "P1" as ModuleKey, component: "AS1P1TransformationsLessonWIDGET002" },
  "AS1-Quadratics-Lesson-MMD-001": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonMMD001" },
  "AS1-Quadratics-Lesson-MMD-002": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonMMD002" },
  "AS1-Quadratics-Lesson-SVG-001": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonSVG001" },
  "AS1-Quadratics-Lesson-TIKZ-001": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonTIKZ001" },
  "AS1-Quadratics-Lesson-TIKZ-002": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonTIKZ002" },
  "AS1-Quadratics-Lesson-WIDGET-001": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonWIDGET001" },
  "AS1-Quadratics-Lesson-WIDGET-002": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonWIDGET002" },
  "AS1-Quadratics-Lesson-WIDGET-003": { module: "P1" as ModuleKey, component: "AS1QuadraticsLessonWIDGET003" },
  "AS1-Trig-Transformations-Lesson-MMD-001": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonMMD001" },
  "AS1-Trig-Transformations-Lesson-MMD-002": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonMMD002" },
  "AS1-Trig-Transformations-Lesson-SVG-001": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonSVG001" },
  "AS1-Trig-Transformations-Lesson-TIKZ-001": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonTIKZ001" },
  "AS1-Trig-Transformations-Lesson-TIKZ-002": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonTIKZ002" },
  "AS1-Trig-Transformations-Lesson-TIKZ-003": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonTIKZ003" },
  "AS1-Trig-Transformations-Lesson-TIKZ-004": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonTIKZ004" },
  "AS1-Trig-Transformations-Lesson-TIKZ-005": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonTIKZ005" },
  "AS1-Trig-Transformations-Lesson-WIDGET-001": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonWIDGET001" },
  "AS1-Trig-Transformations-Lesson-WIDGET-002": { module: "P4" as ModuleKey, component: "AS1TrigTransformationsLessonWIDGET002" },
  "AS1-Trigonometry-Lesson-MMD-001": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonMMD001" },
  "AS1-Trigonometry-Lesson-MMD-002": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonMMD002" },
  "AS1-Trigonometry-Lesson-MMD-003": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonMMD003" },
  "AS1-Trigonometry-Lesson-TIKZ-001": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonTIKZ001" },
  "AS1-Trigonometry-Lesson-TIKZ-002": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonTIKZ002" },
  "AS1-Trigonometry-Lesson-TIKZ-003": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonTIKZ003" },
  "AS1-Trigonometry-Lesson-TIKZ-004": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonTIKZ004" },
  "AS1-Trigonometry-Lesson-TIKZ-005": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonTIKZ005" },
  "AS1-Trigonometry-Lesson-TIKZ-006": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonTIKZ006" },
  "AS1-Trigonometry-Lesson-TIKZ-007": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonTIKZ007" },
  "AS1-Trigonometry-Lesson-WIDGET-001": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonWIDGET001" },
  "AS1-Trigonometry-Lesson-WIDGET-002": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonWIDGET002" },
  "AS1-Trigonometry-Lesson-WIDGET-003": { module: "P4" as ModuleKey, component: "AS1TrigonometryLessonWIDGET003" },
  "AS1-Vectors-Lesson-MMD-001": { module: "P8" as ModuleKey, component: "AS1VectorsLessonMMD001" },
  "AS1-Vectors-Lesson-SVG-001": { module: "P8" as ModuleKey, component: "AS1VectorsLessonSVG001" },
  "AS1-Vectors-Lesson-TIKZ-001": { module: "P8" as ModuleKey, component: "AS1VectorsLessonTIKZ001" },
  "AS1-Vectors-Lesson-TIKZ-002": { module: "P8" as ModuleKey, component: "AS1VectorsLessonTIKZ002" },
  "AS1-Vectors-Lesson-TIKZ-003": { module: "P8" as ModuleKey, component: "AS1VectorsLessonTIKZ003" },
  "AS1-Vectors-Lesson-TIKZ-004": { module: "P8" as ModuleKey, component: "AS1VectorsLessonTIKZ004" },
  "AS1-Vectors-Lesson-TIKZ-005": { module: "P8" as ModuleKey, component: "AS1VectorsLessonTIKZ005" },
  "AS1-Vectors-Lesson-WIDGET-001": { module: "P8" as ModuleKey, component: "AS1VectorsLessonWIDGET001" },
  "AS1-Vectors-Lesson-WIDGET-002": { module: "P8" as ModuleKey, component: "AS1VectorsLessonWIDGET002" },
  "AS1-Vectors-Lesson-WIDGET-003": { module: "P8" as ModuleKey, component: "AS1VectorsLessonWIDGET003" },
};
